### ISSUE TITLE
Font `Virgil, Segoe UI Emoji` within SVG - not rendered in Github / Markdown 

### ISSUE THREAD

**Issue by D1no** [excalidraw/excalidraw-vscode#28]
Thank you for this awesome plug in! It really helps to keep design docs in sync with code ❤️ (while not shipping a whole UML work suit)

I was wondering if there is a way to keep the font alive in markdown / github readmes? I'm not to familiar what's possible in the svg format or if there could be a setting to change the font for the svg generation. I.e. to one that is widely available (if that's actually the issue). Aka be it _comic sans_ 🙊

Here what I mean: The font gets lost for people that don't have `Virgil, Segoe UI Emoji`. _Edit: Sorry for speeding up the gif  a little too much...._
![Kapture 2022-04-12 at 01 31 06](https://user-images.githubusercontent.com/2397125/162849756-29899a0d-9129-4f2f-8b8f-63074fef5666.gif)

The generated SVG
![image](https://user-images.githubusercontent.com/2397125/162849962-231f3211-350b-4dbc-b09c-a4c9de8aea52.png)

System

- Mac OS 12.3.1 (latest)
- Excalidraw: v2.0.16
- VS Code: Version: 1.66.1 (Universal)

**Comment by pomdtr** [comment]
Yeah this is an upstream issue, I'm not willing to add custom code in the extension to handle this: https://github.com/excalidraw/excalidraw/issues/1972

I plan to tackle this by allowing the user to edit png files directly, since they work correctly in github markdown #10

**Comment by pomdtr** [comment]
Support for png is live on master. I will not implement custom font embedding logic in this extension.

**Comment by moonrailgun** [comment]
@pomdtr Hi, its some other problem is EVEN i set all font is NORMAL. `@font-face` is also will append by `excalidraw`.

and a incorrect uri with my account name will be expose.(Not good for data-sensitive scene).

![image](https://user-images.githubusercontent.com/6964737/174467616-40546c8f-d17d-4b20-8f39-3cc781bd363c.png)

Another annoying thing, if a image change with other user(without any change), SVG will also change(because of different editor/username/system, like below)

![image](https://user-images.githubusercontent.com/6964737/174467727-1f0e9a7d-a12a-4c58-ae08-6ad1f1835064.png)



BTW: i wanna use svg because of its small and easy to control in SVM
