### ISSUE TITLE
Add color swatch on the side directly

### ISSUE THREAD

**Issue by ericsia** [excalidraw/excalidraw-vscode#31]
I love this extension a lot, it is so good. Now I don't need to open another app to draw, but......
When I am performing a demo to explain what is happening to my students, I need to use a different color for them to easier identify what is happening. But it is very difficult for me to switch colour. So here is my suggestion, are you able to add a color switch right here below, I provided 16 color code to ease you implement it:
```
16 default color - so that on clicking change pen color ❤
FFC114
F6630D
FF0066
E71224
5B2D90
AB008B
CC0066
004F8B
00A0D7
33CCFF
008C3A
66CC00
000000
333333
849398
FFFFFF
```

![image](https://user-images.githubusercontent.com/24624808/163690249-48742b33-e74d-4f16-af5f-46ea095a4cd4.png)
and here is a screenshot representing what i'm thinking.

**Comment by pomdtr** [comment]
Hi @ericsia, I'm glad to hear that you like the extension !

In order to achieve what you want, I would advise to use the excalidraw keyboard shortcuts.
After selectin the pen, you can type the `s` key to reveal the color picker. Then you can use any displayed key to switch to the corresponding color (ex: `d` for green).

If you feel like this is not suffecient for your usecase, please create an issue in the upstream repository : https://github.com/excalidraw/excalidraw/issues.

**Comment by ericsia** [comment]
> 

Well, that is not ideal especially in long term involve in frequently switching between color.
Is it possible for you guys developer make something different for this vscode extension to keep the pallet expanded instead of use `s` to expand it?
I tried to find where did they store the color palette but I couldn't find it, else I could edit it myself

**Comment by pomdtr** [comment]
I try to stay as close to possible to the native excalidraw experience in this extension to limit the amount of code I need to maintain, so I am not willing to add some custom UI in this repository. The code in this respository is the glue between excalidraw and vscode apis.

**Comment by ericsia** [comment]
> I try to stay as close to possible to the native excalidraw experience in this extension to limit the amount of code I need to maintain, so I am not willing to add some custom UI in this repository. The code in this respository is the glue between excalidraw and vscode apis.

I really hope the collor pallete can keep oppening, it just requires a bit of shifting down
![image](https://user-images.githubusercontent.com/24624808/163691723-527b9427-b82b-4c93-806a-a9d7b7967061.png)

how about writing a script to automate patching the pallet? so even next time they update it, running the script will patch it

**Comment by pomdtr** [comment]
If you want to change the behavior of excalidraw, please open an issue / pull request in the excalidraw/excalidraw upstream repository. 
I will not implement any patch to the UI here, because most users want an experience as close as possible to the excalidraw browser version, with the benefits of vscode feature (multiple tabs, version control...)

**Comment by ericsia** [comment]
@pomdtr when I split-view click `s` doesn't show up the pallet thought
![image](https://user-images.githubusercontent.com/24624808/163726926-c918cf2c-d8b3-4293-ac6d-f95c8dbe97e8.png)
