### ISSUE TITLE
Add support for .excalidraw.png extension

### ISSUE THREAD

**Issue by ebonnal** [excalidraw/excalidraw-vscode#32]
It would be really useful to be able to edit `.excalidraw.png` files which embed their scene :pray:. Sometimes it it more convenient to work with png files instead of svg, for example Atlassian's Confluence does [not support svg rendering yet](https://jira.atlassian.com/browse/CONFCLOUD-1762).

**Comment by pomdtr** [comment]
This is already implemented on master !

Here is the most recent version of the extension, you can install it with the `Extensions: Install from VSIX...` command: https://wormhole.app/4WDx6#Oz1ef5KGGZ_mFr5kUajOPw

**Comment by gregmuellegger** [comment]
Hi, I have updated to most recent version released today:
![grafik](https://user-images.githubusercontent.com/88278/164473467-6196b255-0aac-401a-abec-81d1400778c4.png)

But it seems that it is still not able to open the file in excalidraw the editor mode. On open it shows as plain image.

I'm also here because of the reason @bonnal-enzo mentioned: `.excalidraw.svg` is not supported in Confluence.

**Comment by pomdtr** [comment]
Did you use the pre-release ?

See this tweet for a video guide: https://twitter.com/excalidraw/status/1516792418145816576

**Comment by pomdtr** [comment]
I will push the new version soon, I'm just tweaking theme related settings in this pull request: #37

**Comment by gregmuellegger** [comment]
@pomdtr I did not. Sorry for that, wasn't aware of the button. It works!! Thank you that is super awesome!
